### PR TITLE
Add missing host attribute to handle new Papertrail servers

### PR DESCRIPTION
**Pull request by madwork**
Hi,

Unfortunately Papertrail has added a new server logs2.papertrailapp.com (173.247.105.170), and I came across it! So, I added this new host attribute to the cookbook to manage that, with specs and also updated README/metadata.

:white_check_mark: bundle exec rake cookbook:test

### CODE REVIEW

**Comment by madwork** [comment]
With the new chef supermarket, some dependencies have to be updated, that's why the build failed on Travis. I used to manage that to run the tests, but there are somes updates to make:
Berkshelf should be updated to v3.1 to add the new source into the Berksfile, but there are conflicts with dependencies, like the cookbook-development gem, which should use strainer v3.4.0

**Comment by motns** [comment]
Hi @madwork - thanks for the pull request! You're right, the dependencies are massively out of date here, so no wonder the Travis build fails.

The things is, since we no longer use Papertrail, we kind of stopped updating this cookbook (see the notice in the Readme). Would you by any chance be interested in taking over as the maintainer? I could add you as a collaborator on Chef Supermarket so that you can publish new versions.
Alternatively if you're not interested, your changes look good to me, so I'm happy to merge them in now as they are (even with Travis failing) - I'm really busy these days, so I won't really have time to fix the dependencies any time soon (and get Travis passing).

**Comment by madwork** [comment]
Hi @motns,

Sorry, I completely missed the notice.

I find your cookbook really well and it fit perfectly to my needs, and yes, I would be interested in taking over as the maintainer.
However, there is a dependency with the cookbook-development gem and this gem must be updated too. Do you still use it for you recent cookbook ? Do you want keep it as a dependency ?

I'm a bit curious, you have stopped using Papertrail for an homemade solution ?

**Comment by gh2k** [comment]
I've taken over maintenance of this cookbook, and I've merged this into my fork. Thanks, @madwork

**Comment by madwork** [comment]
@gh2k Awesome! :+1:

**Pull request closed without merging**
